/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  mainSidebar: [
    'about',
    'faq',
    {
      type: 'category',
      label: '🕹️ Play CitizenIV',
      collapsible: false,
      items: [
        'install',
	'troubleshoot',
      ]
    },
    {
      type: 'category',
      label: '🔨 Dedicated Server',
      collapsible: false,
      items: [
        'install-server',
	'migrating',
      ]
    },
    {
      type: 'category',
      label: '📙 Scripting Reference',
      collapsible: false,
      items: [
        'resource',
	'functions',
	'events',
	'natives',
      ]
    },
    {
      type: 'category',
      label: '📗 Streaming Reference',
      collapsible: false,
      items: [
        'cdimages',
	'content',
      ]
    },
    {
      type: 'category',
      label: '📘 Game Reference',
      collapsible: false,
      items: [
	'blips',
	'checkpoints',
	'keys',
	'peds',
	'vehicles',
	'vehcols',
	'weapons',
	'weathers',
      ]
    },
  ],
};

module.exports = sidebars;
